#!/bin/bash

echo "Low temperature simulation"
./ising 10 $1 1 t01
echo "Done"
echo "Curie temperature simulation"
./ising 22.69 $1 1 tc
echo "Done"
echo "High temperature simulation"
./ising 100 $1 1 t10
echo "Done"

mkdir -p data/$1
mv t01 data/$1/
mv tc data/$1/
mv t10 data/$1/
echo "Data saved in data/"
