#!/bin/bash

echo "Starting..."
./ising 20 8 2 > data/flips1.dat
echo "1/3 done"
./ising 21 10 2 > data/flips2.dat
echo "2/3 done"
./ising 20 15 2 > data/flips3.dat
echo "All done"
echo "Data saved in data/"
