#!/bin/bash

echo "Starting..."
./src/ising5 > data/data5.dat
echo "L = 5 done"
./src/ising20 > data/data20.dat
echo "L = 20 done"
./src/ising80 > data/data80.dat
echo "L = 80 done"
echo "All done"
echo "Data saved in data/"
