#!/bin/bash

counter=1
while [ $counter -le 100 ]; do
	./ising $((counter)) 5
	counter=$((counter+1))
done
./ising 22.65 5
./ising 22.66 5
./ising 22.67 5
./ising 22.68 5
./ising 22.69 5
./ising 22.70 5
./ising 22.71 5
./ising 22.72 5
./ising 22.73 5
./ising 22.74 5
./ising 22.75 5
