#!/bin/bash

counter=1
while [ $counter -le 100 ]; do
	./ising $((counter)) 20
	counter=$((counter+1))
done

./ising 21.19 20
./ising 21.49 20
./ising 21.79 20
./ising 22.09 20
./ising 22.39 20
./ising 22.69 20
./ising 22.99 20
./ising 23.29 20
./ising 23.59 20
./ising 23.89 20
./ising 24.19 20
