#!/bin/bash

counter=1
while [ $counter -le 100 ]; do
	./ising $((counter)) 80
	counter=$((counter+1))
done
./ising 2.265 80
./ising 2.266 80
./ising 2.267 80
./ising 2.268 80
./ising 2.269 80
./ising 2.27 80
./ising 2.271 80
./ising 2.272 80
./ising 2.273 80
./ising 2.274 80
./ising 2.275 80
