#!/bin/bash

counter=1
while [ $counter -le 100 ]; do
	./ising $((counter)) 20
	counter=$((counter+1))
done
./ising 22.65 20
./ising 22.66 20
./ising 22.67 20
./ising 22.68 20
./ising 22.69 20
./ising 22.70 20
./ising 22.71 20
./ising 22.72 20
./ising 22.73 20
./ising 22.74 20
./ising 22.75 20
