#!/bin/bash

counter=1
while [ $counter -le 100 ]; do
	./ising $((counter)) 80
	counter=$((counter+1))
done
./ising 22.65 80
./ising 22.66 80
./ising 22.67 80
./ising 22.68 80
./ising 22.69 80
./ising 22.70 80
./ising 22.71 80
./ising 22.72 80
./ising 22.73 80
./ising 22.74 80
./ising 22.75 80
